-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- inboundInspection
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inboundInspection' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inboundInspection');
  END LOOP;
END
$authz$;
ALTER TABLE public."inboundInspection" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inboundInspection" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inboundInspection" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inboundInspection" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inboundInspection" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inboundInspectionHistory
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inboundInspectionHistory' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inboundInspectionHistory');
  END LOOP;
END
$authz$;
ALTER TABLE public."inboundInspectionHistory" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inboundInspectionHistory" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inboundInspectionHistory" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));

-- inboundInspectionSample
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inboundInspectionSample' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inboundInspectionSample');
  END LOOP;
END
$authz$;
ALTER TABLE public."inboundInspectionSample" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inboundInspectionSample" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inboundInspectionSample" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inboundInspectionSample" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inboundInspectionSample" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inboundInspectionSampleMeasurement
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inboundInspectionSampleMeasurement' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inboundInspectionSampleMeasurement');
  END LOOP;
END
$authz$;
ALTER TABLE public."inboundInspectionSampleMeasurement" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inboundInspectionSampleMeasurement" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inboundInspectionSampleMeasurement" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inboundInspectionSampleMeasurement" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inboundInspectionSampleMeasurement" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inspectionDependency
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inspectionDependency' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inspectionDependency');
  END LOOP;
END
$authz$;
ALTER TABLE public."inspectionDependency" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inspectionDependency" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inspectionDependency" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inspectionDependency" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inspectionDependency" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inspectionInProcess
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inspectionInProcess' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inspectionInProcess');
  END LOOP;
END
$authz$;
ALTER TABLE public."inspectionInProcess" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inspectionInProcess" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inspectionInProcess" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inspectionInProcess" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inspectionInProcess" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inspectionLot
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inspectionLot' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inspectionLot');
  END LOOP;
END
$authz$;
ALTER TABLE public."inspectionLot" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inspectionLot" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inspectionLot" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inspectionLot" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inspectionLot" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inspectionReceipt
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inspectionReceipt' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inspectionReceipt');
  END LOOP;
END
$authz$;
ALTER TABLE public."inspectionReceipt" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inspectionReceipt" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inspectionReceipt" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inspectionReceipt" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inspectionReceipt" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inspectionSampleMeasurement
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inspectionSampleMeasurement' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inspectionSampleMeasurement');
  END LOOP;
END
$authz$;
ALTER TABLE public."inspectionSampleMeasurement" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inspectionSampleMeasurement" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inspectionSampleMeasurement" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inspectionSampleMeasurement" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inspectionSampleMeasurement" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- inspectionTrackedEntity
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'inspectionTrackedEntity' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'inspectionTrackedEntity');
  END LOOP;
END
$authz$;
ALTER TABLE public."inspectionTrackedEntity" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."inspectionTrackedEntity" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."inspectionTrackedEntity" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."inspectionTrackedEntity" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."inspectionTrackedEntity" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- itemInspectionPolicy
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'itemInspectionPolicy' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'itemInspectionPolicy');
  END LOOP;
END
$authz$;
ALTER TABLE public."itemInspectionPolicy" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."itemInspectionPolicy" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."itemInspectionPolicy" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."itemInspectionPolicy" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."itemInspectionPolicy" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- itemPackaging
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'itemPackaging' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'itemPackaging');
  END LOOP;
END
$authz$;
ALTER TABLE public."itemPackaging" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."itemPackaging" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."itemPackaging" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."itemPackaging" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."itemPackaging" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_delete'))::text[]));

-- jobOperationInspectionPlan
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'jobOperationInspectionPlan' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'jobOperationInspectionPlan');
  END LOOP;
END
$authz$;
ALTER TABLE public."jobOperationInspectionPlan" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."jobOperationInspectionPlan" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."jobOperationInspectionPlan" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."jobOperationInspectionPlan" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."jobOperationInspectionPlan" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- methodOperationInspectionPlan
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'methodOperationInspectionPlan' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'methodOperationInspectionPlan');
  END LOOP;
END
$authz$;
ALTER TABLE public."methodOperationInspectionPlan" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."methodOperationInspectionPlan" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."methodOperationInspectionPlan" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."methodOperationInspectionPlan" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."methodOperationInspectionPlan" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- nonConformanceInboundInspection
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'nonConformanceInboundInspection' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'nonConformanceInboundInspection');
  END LOOP;
END
$authz$;
ALTER TABLE public."nonConformanceInboundInspection" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."nonConformanceInboundInspection" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."nonConformanceInboundInspection" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."nonConformanceInboundInspection" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."nonConformanceInboundInspection" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));
