-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- quotePart
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'quotePart' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'quotePart');
  END LOOP;
END
$authz$;
ALTER TABLE public."quotePart" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."quotePart" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."quotePart" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."quotePart" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."quotePart" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));

-- toolLifeLedger
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'toolLifeLedger' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'toolLifeLedger');
  END LOOP;
END
$authz$;
ALTER TABLE public."toolLifeLedger" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."toolLifeLedger" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."toolLifeLedger" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_update'))::text[]));
